{"name": "Создание пользователя который уже есть в системе", "status": "passed", "description": "При создании дублирующего пользователя срабатывает allert ", "start": 1732633722766, "stop": 1732633724001, "uuid": "e2dfc65a-c4ff-43ce-9006-4dc6b1fc72a2", "historyId": "511af5c3d1ba0594e424965a597653ae", "testCaseId": "511af5c3d1ba0594e424965a597653ae", "fullName": "tests.test_create_user.TestCreateUser#test_create_double_user_error", "labels": [{"name": "suite", "value": "Создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Raybook"}, {"name": "thread", "value": "3488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}